apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base.yaml
namespace: hogehoge
patches:
  - path: ./linux-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      # name:
      # namespace:
      # labelSelector:
      # annotationSelector:
